version: '1'

services:
  db: 
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: likenow_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: