#
POST http://localhost:3000/feedback/sendFeedback
Content-Type: application/json

{
  "userId": "cmbc0s0wv0000q47wtb3ln21f",
  "message": "Transcrição original: Então, eu acabei de sair da reunião aqui com o Jefferson, e o Jefferson infelizmente tá me tratando de uma forma que eu não gosto, ele não tem escutado as minhas opiniões, não tem realmente me dado nenhuma atenção, então eu gostaria de ter um melhor tratamento do meu chefe, e por esse motivo que eu tô mandando o áudio."
}



####
GET http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWJjODV1MTUwMDAycTRqcnBqeWVqeG45IiwiaWF0IjoxNzQ4Njk1NjE3LCJleHAiOjE3NDg3ODIwMTd9.OGJRdTM-hwYqwYdIN-8FR7KzO011Fy9yzN4iqXdfrSg


###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "user123"  
}
